    database:
        image: postgres
        ports:
          - "5432"
    
    web:
        build: .
        tty: true
        stdin_open: true
        volumes:
          - .:/blog/
        # working_dir: /blog
        command: /bin/bash #stack exec -- yesod devel
        environment:
          - HOST=0.0.0.0
          - PGUSER=postgres
          - PGPASS
          - PGHOST=database
        ports:
          - "3000:3000"
        links:
          - database
