web:
    image: blog_web:latest 
    volumes:
      - .:/blog/
    tty: true
    stdin_open: true 
    working_dir: /blog
    ports:
        - "3000:3000"
    command: stack exec -- blog
    environment:
      - HOST=0.0.0.0
      - APPROOT=http://localhost:3000
      - PGUSER=postgres
      - PGPASS
      - PGHOST=postgres
    links:
        - postgres

database:
    extends:
        file: common.yml
        service: database

postgres:
    image: postgres:latest
    volumes_from:
      - database
    ports:
      - "5432:5432"
