web:
    build: .
    volumes:
      - .:/blog/
    tty: true
    stdin_open: true 
    working_dir: /blog
    ports:
        - "3000:3000"
    command: stack exec -- yesod devel
    environment:
      # - PATH=/root/.local/bin:$PATH
      - HOST=0.0.0.0
      - APPROOT=http://localhost:3000
      - PGUSER=postgres
      - PGPASS
      - PGHOST=postgres
    links:
        - postgres

postgres:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
      - "5432:5432"

database:
    image: postgres
    volumes_from:
      - postgres
