web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/blog/
    # working_dir: /blog
    command: stack test
    environment:
      - HOST=0.0.0.0
      - PGUSER=postgres
      - PGPASS
      - PGHOST=postgres
    ports:
      - "3000:3000"
    links:
      - postgres

postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - database
    ports:
      - "5432:5432"
        
database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
