web:
    restart: always
    image: shuny/blog_web:latest
    tty: true
    stdin_open: true 
    working_dir: /blog
    ports:
        - "3000:3000"
    command: stack exec -- blog
    environment:
      - HOST=0.0.0.0
      - APPROOT=http://45.55.91.101:3000
      - PGUSER=postgres
      - PGPASS
      - PGHOST=postgres
    links:
        - postgres

postgres:
    restart: always
    image: postgres:latest
    volumes: 
      - /var/lib/postgresql
    ports:
      - "5432:5432"

database:
    image: postgres
    restart: always
    volumes_from:
      - postgres

