    database:
        image: postgres
        ports:
          - "5432"
    
    web:
        image: shuny/blog_web:latest
        # volumes:
            # - .:/blog
        tty: true
        stdin_open: true 
        # working_dir: /code/myApp
        command: stack exec -- .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/build/blog/blog
        environment:
          - HOST=0.0.0.0
          - PGUSER=postgres
          - PGPASS
          - PGHOST=database
        ports:
            - "3000:3000"
        links:
            - database
